### ISSUE TITLE
Feature: Add device DevEUI in device list

### ISSUE THREAD

**Issue by Metal-Mighty** [CGI-FR/IoT-Hub-Portal#998]
**Is your feature request related to a problem? Please describe.**
I would like the DevEUI of the sensor to be displayed next to its "Display name".

**Describe the solution you'd like**
```html 
<td data-label="Device" style="word-break: break-all;" class="mud-table-cell">
  <span>Sensor01</span>
  <span class="device_deveui">00A83F7000002EE0</span>
</td>
```

```css 
.device_deveui {
  color: lightgray;
  margin-left: 5px;
  font-size: .750rem;
}
```
![image](https://user-images.githubusercontent.com/5247527/181719169-5e52472a-0dec-4dbe-82ff-e9b8e0d98ed0.png)

**Describe alternatives you've considered**
-

**Additional context**
-
